# ---------- NOTE: This file is auto-generated by AgentCore CLI (Import from Bedrock Agents). ----------
# Use this agent definition as a starting point for your custom agent implementation.
# Review the generated code, evaluate agent behavior, and make necessary changes before deploying.
# -------------------------------------------------------------------------------------------------

import json, sys, os, re, io, uuid, asyncio
from datetime import datetime
from typing import Annotated
import boto3

# In-memory stub data — the same fixtures the Phase 1 Lambdas use, moved
# in-process so the @tool functions run without Lambda invocations.
OWNERS = {
    "9612f6c4-b7ff-4d82-b113-7b605e188ed9": {
        "id": "9612f6c4-b7ff-4d82-b113-7b605e188ed9",
        "firstname": "John",
        "lastname": "Doe",
        "homeAirport": "KJFK",
    }
}

PASSENGERS = {
    "9612f6c4-b7ff-4d82-b113-7b605e188ed9": [
        {"firstname": "Jill", "lastname": "Doe", "homeAirport": "KJFK",
         "ownerRelationship": "Wife", "age": 39},
        {"firstname": "Jane", "lastname": "Doe", "homeAirport": "KJFK",
         "ownerRelationship": "Daughter", "age": 20},
        {"firstname": "Jenny", "lastname": "Doe", "homeAirport": "KJFK",
         "ownerRelationship": "Daughter", "age": 24},
    ]
}

from bedrock_agentcore.runtime import BedrockAgentCoreApp

app = BedrockAgentCoreApp()

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from strands import Agent, tool
from strands.agent.conversation_manager import SlidingWindowConversationManager
from strands.models import BedrockModel
from strands.types.content import Message
from strands_tools import current_time  # built-in clock tool


llm_ORCHESTRATION = BedrockModel(
    model_id="us.anthropic.claude-sonnet-4-6",
    region_name="us-east-1",
    temperature=1,
    max_tokens=2048,
)

ORCHESTRATION_TEMPLATE = """You are an AI assistant for a private aviation company. You help book private jet
reservations for aircraft owners and their families.

When a user requests a trip:
1. Look up the owner's information using their owner ID to find their home airport.
2. Look up the owner's registered passengers (family members).
3. Determine the departure airport (owner's home airport) and arrival airport based on the destination.
4. Compute the flight date/time based on the user's request.
5. Book the reservation with all passengers.

Important:
- Disney World is near Orlando, Florida. The nearest airport is KMCO (Orlando International).
- Always use ICAO airport codes (e.g., KJFK, KMCO, KLAX).
- When the user says "family", include all registered passengers for the owner.
- Format dates in ISO 8601 format."""


# --- Action Group Tools ---
action_group_tools = []

@tool
def get_owner_info(ownerId: str) -> str:
    """Retrieve the profile of a private jet owner — name and home airport — by owner ID."""
    if ownerId in OWNERS:
        return json.dumps(OWNERS[ownerId])
    return json.dumps({"error": f"Owner '{ownerId}' not found."})

action_group_tools.append(get_owner_info)

@tool
def get_passengers(ownerId: str) -> str:
    """List the family members and registered passengers associated with an owner."""
    if ownerId in PASSENGERS:
        return json.dumps({"ownerId": ownerId, "passengers": PASSENGERS[ownerId]})
    return json.dumps({"error": f"No passengers found for owner '{ownerId}'."})

action_group_tools.append(get_passengers)

@tool
def book_reservation(date: str, passengers: str, departureAirport: str, ownerId: str, arrivalAirport: str) -> str:
    """Book a private jet reservation for the owner and their registered passengers."""
    owner = OWNERS.get(ownerId, {"firstname": "Unknown", "lastname": "Owner"})
    try:
        pax = json.loads(passengers) if isinstance(passengers, str) else passengers
    except (json.JSONDecodeError, TypeError):
        pax = []

    return json.dumps({
        "confirmationId": f"PVT-{uuid.uuid4().hex[:8].upper()}",
        "ownerId": ownerId,
        "primaryPassenger": f"{owner['firstname']} {owner['lastname']}",
        "date": date,
        "departure": departureAirport,
        "arrival": arrivalAirport,
        "passengers": pax,
        "totalPassengers": len(pax) + 1,
        "status": "CONFIRMED",
        "bookedAt": datetime.utcnow().isoformat() + "Z",
    })

action_group_tools.append(book_reservation)


# --- Agent Setup ---
tools = [current_time]
tools_used = set()
tools += action_group_tools


def make_msg(role, text):
    return {
        "role": role,
        "content": [{"text": text}]
    }

def inference(model, messages, system_prompt=""):
    async def run_inference():
        results = []
        async for event in model.stream(messages=messages, system_prompt=system_prompt):
            results.append(event)
        return results

    response = asyncio.run(run_inference())

    text = ""
    for chunk in response:
        if "contentBlockDelta" not in chunk:
            continue
        text += chunk["contentBlockDelta"].get("delta", {}).get("text", "")

    return text

_agent = None
first_turn = True
last_input = ""
user_id = ""

# agent update loop
def get_agent():
    global _agent
    if _agent is None:
        system_prompt = ORCHESTRATION_TEMPLATE
        _agent = Agent(
            model=llm_ORCHESTRATION,
            system_prompt=system_prompt,
            tools=tools,
            conversation_manager=SlidingWindowConversationManager()
        )
    return _agent

def invoke_agent(question: str):
    global last_input
    last_input = question
    agent = get_agent()

    original_stdout = sys.stdout
    sys.stdout = io.StringIO()
    response = agent(question)
    sys.stdout = original_stdout
    return response


@app.entrypoint
async def invoke(payload, context):
    try:
        session_id = context.session_id or payload.get("sessionId", uuid.uuid4().hex[:8])

        tools_used.clear()
        agent_query = payload.get("prompt", "")
        if not agent_query:
            yield "No query provided, please provide a 'prompt' field in the payload."
            return

        agent_result = invoke_agent(agent_query)

        tools_used.update(list(agent_result.metrics.tool_metrics.keys()))
        response_content = str(agent_result)

        yield response_content if response_content else "No response."
    except Exception as e:
        yield f"Error: {e}"


if __name__ == "__main__":
    app.run()
